name: PR Tests
on:
  pull_request:

jobs:
  coverage-goshujin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: goshujin

      - name: "Install Node"
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"

      - name: "Coverage"
        run: |
          yarn install
          yarn build:frontend
          yarn test
          yarn coverage

      - name: "Upload Coverage"
        uses: actions/upload-artifact@v4
        with:
          name: coverage-goshujin
          path: coverage

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: "Install Node"
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"

      - name: "Install Deps"
        run: yarn install

      - name: "Build Frontend"
        run: yarn build:frontend

      - name: "Test"
        run: |
          yarn prettier -c .
          yarn eslint .
          yarn test

      - name: "Run Coverage"
        run: yarn coverage

      - name: "Upload Coverage"
        uses: actions/upload-artifact@v4
        with:
          name: coverage-head
          path: coverage

  report-coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Download HEAD coverage artifacts"
        uses: actions/download-artifact@v4
        with:
          name: coverage-head
          path: coverage

      - name: "Download goshujin coverage artifacts"
        uses: actions/download-artifact@v4
        with:
          name: coverage-goshujin
          path: coverage-goshujin

      - name: "Report Coverage"
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          json-summary-compare-path: coverage-goshujin/coverage-summary.json
